config:
  host: devx-helloworld-springboot-2yuzq
  namespace: devx-helloworld-springboot-2yuzq-service-dev
  image:
    name: uswest2fpmt.jfrog.io/devx-helloworld-springboot-2yuzq-docker-dev-local/devx-helloworld-springboot-2yuzq
    tag: v0.0.1
